const boletoControllers = require('./boletoControllers')
const impressaoControlllers = require('./impressaoControllers')
const emailControllers = require('./emailControllers')
const remessaControllers = require('./remessaControllers')
const retornoControllers = require('./retornoControllers')
